jabardigitalservice/portal-jabar-services

- core-service/src/database/migrations/20210914162305_create_feedback_table.down.sql
- core-service/src/database/migrations/20210914162305_create_feedback_table.up.sql
- core-service/src/delivery/http/feedback_handler.go
- core-service/src/delivery/http/handlers.go
- core-service/src/domain/feedback.go
- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/repositories/mysql/mysql.go
- core-service/src/repositories/mysql/mysql_feedback.go
- core-service/src/usecases/feedback_ucase.go
- core-service/src/usecases/usecases.go
- add feedbacks table
- add feedback domain & store endpoint
> Feature feedback

- core-service/src/delivery/http/middleware/middleware.go
- cors: allow methods ("GET, POST, PUT, DELETE, OPTIONS")
- corrected sentry trx name
cc @jabardigitalservice/jds-backend
> cors allow methods

- core-service/src/database/migrations/1629281242_initialize_schema.down.sql
- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/delivery/http/featured_program_handler.go
- core-service/src/delivery/http/handlers.go
- core-service/src/domain/featured_program.go
- core-service/src/domain/jsonhandle.go
- core-service/src/repositories/mysql/mysql.go
- core-service/src/repositories/mysql/mysql_featured_program.go
- core-service/src/usecases/featured_program_ucase.go
- core-service/src/usecases/usecases.go
- (+) featured_programs table
- (+) featured-program's fetch endpoint  (repo, ucase, http handler)
- (+) alias `JSONStringSlices` for []string to handle `mysql json_array`
- (+) json unmarshal handler
> featured-program's fetch endpoint 

- core-service/src/delivery/http/news_handler.go
- core-service/src/repositories/mysql/mysql_news.go
(+) add news category filter
title: FIlter Kategori Berita
participants: @khihadysucahyo @novansyaah @fimz17
> add news category filter

- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- add news banner struct
- add news banner repo & usecase
- add news banner endpoint
title: Menembahkan endpoint untuk news banner
participants: @khihadysucahyo @rachadiannovansyah @firmanJS @ayocodingit @setiadijoe
> Feature news banner

- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- add headline news endpoint
title: Menambahkan endpoint headline news
participants: @khihadysucahyo @rachadiannovansyah @firmanJS
> add headline news endpoint

- core-service/src/config/cors.go
- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/news.go
- core-service/src/modules/feedback/delivery/http/feedback_handler.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
- core-service/src/modules/news/usecase/news_ucase.go
- add news share counter
- cors: allow patch method
- Public API: Check and verify the recaptcha response token
title: Menambahkan news share counter
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @ayocheckout
> News share counter

- core-service/src/modules/news/delivery/http/news_handler.go
Overview:
- Fixing removed routes 
> add route for headline

- core-service/src/domain/featured_program.go
- core-service/src/modules/featured-program/delivery/http/featured_program_handler.go
- core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go
Overview:
- Add multiplechoice for filter category featured program
- so FE can send params like this `{base_url}/v1/featured-params?cat[]=kesehatan&cat[]=pendidikan`
that's params has been discussed and accepted by Frontend team
Evidence:
title: Menambahkan multiple filter kategori pada Program Unggulan
participants: @rachadiannovansyah @setiadijoe @ayocodingit @khihadysucahyo
> add multiplechoice filter for category in featured program

- core-service/src/domain/featured_program.go
- core-service/src/domain/result.go
- core-service/src/modules/featured-program/delivery/http/featured_program_handler.go
- core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go
- core-service/src/modules/featured-program/usecase/featured_program_ucase.go
Overview:
- Add metadata for counting data each response
- Add metadata for get last updated featured programs
Overview:
title: Menambahkan custom meta data program unggulan
> add counting and last update on metadata

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- add endpoint: get news by slug
- `ALTER table news modify slug varchar(100) UNIQUE NOT NULL;`
title: Menambahkan endpoint get berita by slug
participants: @khihadysucahyo @rachadiannovansyah @firmanJS @ayocodingit
> add endpoint: get news by slug

- core-service/src/modules/news/usecase/news_ucase.go
Overview:
- Add tags on detail slug
Evidence:
title: Add multiple tags on detail slug
participants: @rachadiannovansyah @firmanJS @khihadysucahyo
> add multiple tags on detail slug

- core-service/src/domain/request.go
- core-service/src/modules/search/repository/elastic/elastic_search.go
- added search sort function
title: Menambah sort search
> sort search

- core-service/src/modules/search/repository/elastic/elastic_search.go
- retrieve selected fields
- enable fuzziness
cc @jabardigitalservice/jds-backend 
title: retrieve selected fields & enable fuzziness
> retrieve selected fields & enable fuzziness

- core-service/src/modules/search/delivery/http/search_handler.go
- core-service/src/modules/search/repository/elastic/elastic_search.go
Overview:
- Add fuzziness on suggest
Evidence:
title: add fuzziness on suggest
participants: @rachadiannovansyah @firmanJS @khihadysucahyo @ayocodingit
> add fuzziness on suggest

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/event.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Add status on api events list + detail
Evidence:
title: add status on agenda list
participants: @rachadiannovansyah @ayocodingit @firmanJS
> Add status on agenda list cms

- core-service/src/modules/featured-program/delivery/http/featured_program_handler.go
- core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go
Overview:
- Fixing error 500 when no rows in result multiple-choice category program
- Give an empty array if no data in the result
Evidence:
title: Fixing error 500 when no rows in the result 
participants: @rachadiannovansyah @rindibudiaramdhan @sandisunandar99 @firmanJS
> fixing bug on handling if no rows in result

- core-service/src/domain/event.go
- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
- core-service/src/modules/event/usecase/event_ucase.go
Overview:
- Add new endpoint API store agenda CMS
- Add validation + check existed
Evidence:
title: Module create agenda with validating & check existed
participants: @rachadiannovansyah @firmanJS @sandisunandar99 @tukangremot @rindibudiaramdhan @khihadysucahyo @ayocodingit
> Module create agenda with validate + check existed

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/event.go
- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
- core-service/src/modules/event/usecase/event_ucase.go
Overview:
- Add endpoint delete agenda (within soft delete flagging)
- Add schema field `deleted_at`
Evidence:
title: Module soft delete flag agenda IPJ
participants: @rachadiannovansyah @khihadysucahyo @ayocodingit @sandisunandar99 @firmanJS
> Module soft delete flag agenda IPJ

- core-service/src/domain/event.go
- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
- core-service/src/modules/event/usecase/event_ucase.go
Overview:
- Endpoint update agenda
Evidence:
title: add endpoint update agenda CMS IPJ
> module update agenda

- core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go
Minor:
- Adjustment total when filtered featured programs
> adjustment total when filter featured programs

- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Fixing bug data still appear even was deleted
Evidence:
title: Memperbaiki soft delete agenda jabar
participants: @rachadiannovansyah @tukangremot @rizkyrmsyah @rindibudiaramdhan @khihadysucahyo @ayocodingit
> not showing data if was deleted (Soft delete)

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/auth.go
- core-service/src/domain/user.go
- core-service/src/modules/auth/delivery/http/auth_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- validation login
- added user photo
title: validation login
participants: @khihadysucahyo @rachadiannovansyah @tukangremot @rizkyrmsyah @ayocodingit @firmanJS
> validation login

- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- fixing pagination on list agenda
Evidence:
title: fixing pagination on list event
participants: @rachadiannovansyah @khihadysucahyo @sandisunandar99 @tukangremot @rizkyrmsyah @rindibudiaramdhan @indraprasetya154 @ayocodingit
> fixing pagination on list event

- core-service/src/modules/user/repository/mysql/mysql_user.go
- handle sql err no rows, returning an empty struct instead of err
title: handle sql err no rows
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @tukangremot @rizkyrmsyah
> handle sql err no rows

- core-service/src/cmd/server/repository.go
- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/data_tag.go
- core-service/src/domain/data_tags.go
- core-service/src/domain/news.go
- core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go
- core-service/src/modules/data-tags/repository/mysql/mysql_data_tags.go
- core-service/src/modules/event/usecase/event_ucase.go
- core-service/src/modules/news/usecase/news_ucase.go
- core-service/src/modules/tag/repository/mysql/mysql_tag.go
Overview:
- sync data tags with tags suggestions on event
Evidence:
title: sync data tag from the tag when storing an event
participants: @rachadiannovansyah @khihadysucahyo @indraprasetya154 @ayocodingit @bangunbagustapa @Ibwedagama
> sync data tag from the tag when storing an event

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go
- core-service/src/modules/tag/repository/mysql/mysql_tag.go
Overview:
- renaming table with plural
> change naming table with plural

- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Add sorting by params on list event
Evidence:
title: add sorting by params on list agenda
participants: @rachadiannovansyah @khihadysucahyo @tukangremot @rizkyrmsyah @ayocodingit
> add sorting by params on list agenda

- core-service/src/cmd/main.go
- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/config/aws.go
- core-service/src/config/config.go
- core-service/src/domain/media.go
- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/modules/media/delivery/http/media_handler.go
- core-service/src/modules/media/usecase/media_ucase.go
- core-service/src/utils/connection.go
- setup aws client config
- added was SDK mod
- refactor repo layer
-added media gallery module
- reviewing related to separation of concern
- request validation
- using go rouitine
title: handle Init Feature Media Gallery
participants: @khihadysucahyo @rachadiannovansyah @tukangremot @rizkyrmsyah @ayocodingit
> Init Feature Media Gallery

- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Add and rename routes agenda for portal
- Add flagging agenda portal
cc : @jabardigitalservice/jds-backend 
Evidence:
title: Add flagging on endpoint portal & cms
> Separate endpoint list agenda portal

- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/news.go
- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
- core-service/src/modules/news/usecase/news_ucase.go
- core-service/src/modules/user/delivery/http/user_handler.go
- Feature create news
- update init schema news
- FIXME: authenticated variables must be global variables to be accessible everywhere
title: Feature create news
participants: @khihadysucahyo @tukangremot @rachadiannovansyah @ayocodingit
> Feature create news

- core-service/src/domain/user.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- append unit on author
title: append unit on author
> append unit on author

- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- minor fixing bug query
cc : @jabardigitalservice/jds-backend 
Evidence:
title: fixing minor bug query variable
participants: @rachadiannovansyah @khihadysucahyo @sandisunandar99 @rindibudiaramdhan @ayocodingit
> fixing minor bug query variable

- core-service/src/database/migrations/1629281242_initialize_schema.up.sql
- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- remove user contstraint on news author
- added update news endpoint
- wrap up store tags
- FIXME: authenticated variables must be global variables to be accessible everywhere
title: news edit feature
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @tukangremot
> Feature news edit

- core-service/src/cmd/server/usecase.go
- core-service/src/domain/user.go
- core-service/src/modules/auth/usecase/auth_ucase.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- append unit obj on user
title: Menambahkan objek perangkat daerah pada user
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @rindibudiaramdhan
> append unit obj on user

- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/usecase.go
- core-service/src/domain/tag.go
- core-service/src/modules/tag/delivery/http/tag_handler.go
- core-service/src/modules/tag/repository/mysql/mysql_tag.go
- core-service/src/modules/tag/usecase/tag_usecase.go
Overview:
- add master data tags for suggestion
Evidence:
title: add master data for suggest tags
> Add master data for suggest tags

- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Add filter params for type and category
Evidence:
title: Menambahkan filter param untuk type dan kategori
parcipants: @rachadiannovansyah @khihadysucahyo @sandisunandar99 @rizkyrmsyah @rindibudiaramdhan @indraprasetya154 @ayocodingit
> add filter params for type and category event

- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/usecase.go
- core-service/src/domain/area.go
- core-service/src/modules/area/delivery/http/area_handler.go
- core-service/src/modules/area/repository/mysql/mysql_area.go
- core-service/src/modules/area/usecase/area_ucase.go
- added area endpoint
title: Menambahkan endpoint area
> added area module

- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
Overview:
- Add params filter news by status
Evidence:
title: Menambahkan param filter berita berdasarkan status berita
participants: @rachadiannovansyah @khihadysucahyo @ayocodingit @rindibudiaramdhan
> add params filter news by status

- core-service/src/domain/news.go
- core-service/src/helpers/converter.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
- core-service/src/modules/news/usecase/news_ucase.go
- select is_live prop and adjust news filter
- added nulltime handler
- use is_live filter on news banner and headline endpoints
title: major update on filtering published news
participants: @khihadysucahyo @rachadiannovansyah @rindibudiaramdhan
> major update on filtering published news

- service-worker/src/go.mod
- service-worker/src/go.sum
- service-worker/src/job/news_archive_job.go
- service-worker/src/job/news_publishing_job.go
- adjust publishing query & added log rows affected
title:  adjust publishing query & added log rows affected
> adjust publishing query & added log rows affected

- core-service/src/domain/news.go
- core-service/src/helpers/converter.go
- core-service/src/helpers/setters.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- added convert string to time helper
- added setter: prop live news
- set published_at fillable on news request struct
- append publiahed_at on publishing in news update
title: chores in news publishing
> chores in news publishing

- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/20220225161438_add_column_duration_in_news_table.down.sql
- core-service/src/database/migrations/20220225161438_add_column_duration_in_news_table.up.sql
- core-service/src/domain/news.go
- core-service/src/modules/area/repository/mysql/mysql_area.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
- core-service/src/modules/news/usecase/news_ucase.go
- fill area details on news
- added news duration
title: Chore news detail
participants: @khihadysucahyo
> Chore news detail

- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/20220301141702_add_column_nip_occupation_on_users_table.down.sql
- core-service/src/database/migrations/20220301141702_add_column_nip_occupation_on_users_table.up.sql
- core-service/src/domain/role.go
- core-service/src/domain/unit.go
- core-service/src/domain/user.go
- core-service/src/helpers/getters.go
- core-service/src/modules/auth/usecase/auth_ucase.go
- core-service/src/modules/role/repository/mysql/mysql_role.go
- core-service/src/modules/unit/delivery/http/unit_handler.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
- portal-jabar.code-workspace
- added user profile endpoint
- added role module
- added migration (alter add column nip, occupation)
- use pointer string instead of nullstring
- added user profile into user module
- Update profile validation
title: Fetaure user profile
> Fetaure user profile

- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
- added change-password usecase
title: added change-password endpoint
> added change-password usecase

- core-service/src/domain/user.go
- core-service/src/helpers/mapper.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/usecase/user_usecase.go
- user profile: allowed partial update
- adjust request validator rule
title: user profile: allowed partial update
> user profile: allowed partial update

- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
Overview:
- add multiple filter categories on news
- fixing meta every filter or search news
Evidence:
title: Fix multiple filter on news
> Fix multiple filter on news

- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- fix issue combination filter + search not working properly
- fix bug sorting
Evidence:
title: Fixing issue combination filter & search
> Fixing issue combination filter & search Agenda

- core-service/src/domain/news.go
- core-service/src/helpers/converter.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
- fix pointer
title: fix pointer
> fix pointer

- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
Overview:
- sort by author using left join by users table
TODO:
- fixing warning query
cc: @khihadysucahyo @jabardigitalservice/jds-backend 
Evidence:
title:  add sort by author news using left join to users
> wip sort by author using left join to users

- core-service/src/modules/news/repository/mysql/mysql_news.go
Overview:
- add pointer each field on filter Fetch news endpoint
> add pointing to each filter att

- core-service/src/helpers/converter.go
- adjust news slug
title: adjust news slug
> adjust news slug

- core-service/src/domain/event.go
- core-service/src/domain/news.go
Overview:
- add validation enum on struct
Evidence:
title: add validation enum on struct
> add layer validation enum on struct

- core-service/src/domain/registration_invitation.go
- core-service/src/modules/registration-invitation/delivery/http/registration_invitation_handler.go
- core-service/src/modules/registration-invitation/usecase/registration_invitation_ucase.go
authorize reg invitation token
- added RegistrationInvitationClaim struct
- added Authorize usecase interface
- added logic implementation of authorize usecase
- add function user registration by invitation on user domain
title: authorize reg invitation token
> authorize reg invitation token

- core-service/src/helpers/notification.go
> fix destination mail

- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
Overview:
- add endpoint list anggota
- list anggota is merging from 2 tables (users + registration_invitations)
Next Todo:
- add value status and last_active from both tables
Evidence:
title: endpoint akun registrasi member
> create endpoint list anggota

- core-service/src/domain/errors.go
- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
user nip validation
- added check user nip endpoint
- check nip before store/update
title: user nip validation
> User nip validation

- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
Overview:
- add endpoint user detail
- add role object on users list
- refactor endpoint users list
Evidence:
title: Refactor & Add new endpoint detail users invitation
> Add endpoint detail list anggota

- core-service/src/modules/user/delivery/http/user_handler.go
minor:
- remove array on detail response
> fix minor data struct response

- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/20220401151911_alter_role_permissions.sql.down.sql
- core-service/src/database/migrations/20220401151911_alter_role_permissions.sql.up.sql
- core-service/src/domain/auth.go
- core-service/src/domain/permission.go
- core-service/src/domain/role_permission.go
- core-service/src/middleware/permission.go
- core-service/src/modules/auth/delivery/http/auth_handler.go
- core-service/src/modules/auth/usecase/auth_ucase.go
- core-service/src/modules/registration-invitation/delivery/http/registration_invitation_handler.go
- core-service/src/modules/role-permission/repository/mysql/mysql_role_permission.go
setup role permissions
- added roles-permissions migrations
- init role permission
- added & use permission middleware
title: setup role permissions
> setup role permissions

- core-service/src/modules/template/usecase/template_usecase.go
Overview:
- fix bug dynamic params template on endpoint get template
Evidence:
title: fix bug dynamic params template
> fix bug dynamic params template

- core-service/src/domain/user.go
hotifx bug required struct request
cc: @khihadysucahyo @bangunbagustapa
> add omitempty on struct request

- core-service/src/domain/constanta.go
- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/usecase/user_usecase.go
refactor tech debt assign role
- readable assign role administrator
title: refactor tech debt assign role
> refactor tech debt assign role

- core-service/src/cmd/main.go
- core-service/src/cmd/server/handler.go
- core-service/src/config/app.go
- core-service/src/config/config.go
- added app config
- healthcheck endpoint
- github action workflow: build, push registry, and make auto MR to update registry version in gitops repo
title: added app config
> added app config

- core-service/.env.example
- core-service/src/cmd/main.go
- core-service/src/cmd/server/handler.go
- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_helper.go
- core-service/src/modules/news/usecase/news_ucase.go
- regroup path & enhance news domain
title: regroup path & enhance news domain
participants: @rachadiannovansyah
> regroup path & enhance news domain

- core-service/src/helpers/getters.go
- core-service/src/modules/auth/usecase/auth_ucase.go
fix status code error login
- fix status code when user is not active
- fix invalid cred if email is not exists
title: fix status code error login
> fix status code error login

- core-service/src/domain/errors.go
- core-service/src/middleware/jwt.go
- core-service/src/middleware/permission.go
- core-service/src/modules/auth/usecase/auth_ucase.go
- core-service/src/modules/news/delivery/http/news_handler.go
- core-service/src/modules/role-permission/repository/mysql/mysql_role_permission.go
- core-service/src/policies/news_policy.go
- init news policy
- wrap in one Allows function
title: init news policy
> init news policy

- core-service/src/domain/news.go
- core-service/src/helpers/helper.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_helper.go
- core-service/src/modules/news/usecase/news_ucase.go
- core-service/src/policies/news_policy.go
- fix filtering news based on role policy
> fix filtering news based on role policy

- core-service/src/helpers/converter.go
- core-service/src/modules/event/usecase/event_ucase.go
- core-service/src/modules/news/usecase/news_ucase.go
Fix issue tags:
- sub string tags name before store
> Fix issue error tags

- core-service/src/domain/event.go
- core-service/src/helpers/helper.go
- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/repository/mysql/mysql_event.go
- core-service/src/modules/event/repository/mysql/mysql_event_helper.go
- core-service/src/modules/event/usecase/event_ucase.go
fix issue fetch based on his unit
- fix issue fetch based on his unit (no longer can see other OPD event)
- add max length validation **address** request
- refactored fetching event filter
title: fix issue fetch based on his unit (no longer can see other OPD event)
> Fix issues cms

- core-service/src/config/app.go
- core-service/src/domain/user.go
- core-service/src/helpers/notification.go
- core-service/src/modules/registration-invitation/usecase/registration_invitation_ucase.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/usecase/user_usecase.go
- core-service/src/utils/mail.go
fix issues mail sender + config
- adjust receiver mail on usecase **account submission**
- use config mail instead of env variables
title: fix issues mail sender + config
> fix issues mail config

- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
- core-service/src/policies/user_policy.go
added user policy
- added user policy
title: added user policy
> added user policy

- core-service/src/domain/user.go
- core-service/src/modules/user/delivery/http/user_handler.go
- core-service/src/modules/user/repository/mysql/mysql_user.go
- core-service/src/modules/user/usecase/user_usecase.go
improve & cleanup user filter
title: improve & cleanup user filter
participants: @khihadysucahyo @rachadiannovansyah @bangunbagustapa
> improve & cleanup user filter

- core-service/src/cmd/server/handler.go
- core-service/src/modules/event/delivery/http/event_handler.go
- core-service/src/modules/event/delivery/http/public_event_handler.go
separate public endpoint for event
- add public handler agenda
- remove from old handler (cms)
TO DO wait feedback FE
> separate public endpoint for event

- core-service/src/domain/news.go
- core-service/src/modules/news/usecase/news_ucase.go
> adjust news banner/headline response

- core-service/src/domain/event.go
- core-service/src/modules/event/repository/mysql/mysql_event_test.go
unit test fetch event
- adjust unused struct
- add unit test fetch event
- unit test store, update, delete
title: unit test fetch event
> unit test fetch event

- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/domain/mail.go
- core-service/src/modules/mail/repository/redis/redis_mail.go
- core-service/src/modules/registration-invitation/usecase/registration_invitation_ucase.go
- added Enqueue repo to push email into queue
title: mail queue
participants: @khihadysucahyo @bangunbagustapa
> mail queue

- core-service/src/modules/event/repository/mysql/mysql_event_test.go
unit test store & detail event
title: unit test store & detail event
> add unit test store and get by id

- .github/workflows/app-build-push.yml
- .github/workflows/app-release.yml
- .github/workflows/app-worker-build-push.yml
1. News 
2. Event
3. Featured programs
4. User Management
v0.4.0
> added release workflow

- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/20220427025812_create_awards_table.down.sql
- core-service/src/database/migrations/20220427025812_create_awards_table.up.sql
- core-service/src/domain/award.go
- core-service/src/modules/award/delivery/http/award_handler.go
- core-service/src/modules/award/repository/mysql/mysql_award.go
- core-service/src/modules/award/usecase/award_ucase.go
add module awards for selayang pandang jabar
- add new table awards migration
- module fetch and get by id award portal (using public endpoint)
title: add module awards for selayang pandang jabar
> Selayang Pandang Jabar Awards

- core-service/src/modules/award/delivery/http/award_handler.go
- core-service/src/modules/award/repository/mysql/mysql_award.go
add multiple filter category on 'List Prestasi Jabar'
title: add multiple filter category on 'List Prestasi Jabar'
> add multiple filter category on awards

- core-service/src/domain/award.go
- core-service/src/modules/award/delivery/http/award_handler.go
- core-service/src/modules/award/repository/mysql/mysql_award.go
- core-service/src/modules/award/usecase/award_ucase.go
- create endpoint list category awards
- add counter aggreagation category
title: membuat list dan agregasi counter kategori prestasi jabar
> create endpoint list aggregation category awards

- service-worker/src/cmd/main.go
- service-worker/src/job/news_archive_job.go
- service-worker/src/job/news_publishing_job.go
title: esindex: news pubishing
> esindex: news pubishing

- core-service/src/modules/search/repository/elastic/elastic_search.go
title: filter active flag on search
> filter active flag on search

- core-service/src/domain/data_tag.go
- core-service/src/domain/event.go
- core-service/src/domain/news.go
- core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go
- core-service/src/modules/event/usecase/event_ucase.go
- core-service/src/modules/news/usecase/news_ucase.go
checking value type of domain data tags
- add default Constanta for "news" and "event"
- adjust query to check value type of domain
title: fix bug anomaly data tags
> check type of domain when fetching data tags

- core-service/src/cmd/server/usecase.go
- core-service/src/domain/search.go
- core-service/src/modules/news/usecase/news_ucase.go
- core-service/src/modules/search/repository/elastic/elastic_search.go
- core-service/src/modules/search/usecase/search_ucase.go
- akan dibuatkan function untuk prepare the search payload, biar lebih clean & clear seperti shampo
title: added elastic repo for crud function
> added elastic repo for crud function

- core-service/src/modules/unit/repository/mysql/mysql_unit.go
kemarin nambahin WHERE 1=1 ya? ini ketinggalan diubah jga
> fix unit query getbyid

- core-service/src/cmd/migrater/main.go
fix value excerpt dan thumbnail
> update escli sync news

- core-service/src/modules/search/repository/elastic/elastic_search.go
add dynamic sorting elastic search by params
title: menambahkan dinamik sorting elastic berdasarkan params
> add dynamic sorting elastic search by params

- core-service/src/database/migrations/20220602032310_alter_occupation_on_users_table.down.sql
- core-service/src/database/migrations/20220602032310_alter_occupation_on_users_table.up.sql
- core-service/src/domain/user.go
- add migration to alter column length
- change max validation of occupation to 100
title: membuat migrasi untuk mengubah struktur column occupation
> fix occupation validation

- core-service/src/modules/news/usecase/news_ucase.go
- service-worker/src/job/news_publishing_job.go
- fix _**publishing**_ news on elastic (value _is_active_ will be true)
- tidy up code
title: fixing berita yang di publish tidak muncul pada global search
participants: @rachadiannovansyah @ayocodingit @indraprasetya154
> fix publishing news on elastic

- core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_helper.go
- core-service/src/modules/news/usecase/news_ucase.go
- fix bug anomaly slug on news elastic (case status except 'PUBLISHED')
- fix specify type domain on data tag filter
title: memperbaiki anomaly slug pada data elasticsearch
participants: @rachadiannovansyah @ayocodingit @indraprasetya154
> [News] fix unix slug on elastic data news

- core-service/src/helpers/setters.go
Fix issue start date when exceed the review time
- Value of start_date will replace with published_at
- Value of end_date will replace with start_date + duration
title: memperbaiki isu waktu tayang ketika melebihi batas waktu review berita
participants: @rachadiannovansyah @indraprasetya154 @ayocodingit
> [News] Fix issue start date when exceed the review time

- core-service/src/modules/news/usecase/news_ucase.go
- core-service/src/modules/search/repository/elastic/elastic_search.go
Overview
Sync published_at on elastic when updating news
- adjust func Update  on elastic repo
- adjust func Update & UpdateStatus on news usecase
Evidence
title: memperbaiki anomali publish ketika mengupdate berita
> Fix issue update news 

- service-worker/src/cmd/main.go
Overview
adjust job schedule of cron to daily on the midnight
Evidence
title: penyesuaian job schedule service worker
participants: @rachadiannovansyah @rindibudiaramdhan @sandisunandar99
> adjust cron schedule to @daily on the midnight

- core-service/src/modules/news/usecase/news_ucase.go
Overview
fix issue when create news with draft
Evidence
title: fix bug create news with draft
participants: @rachadiannovansyah @indraprasetya154 @ayocodingit @sandisunandar99 @azophy
> fix bug when create news with DRAFT

- core-service/src/config/app.go
- core-service/src/domain/news.go
- core-service/src/helpers/setters.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
Overview
- fix issue pointer insert to elastic
- add new attribute for website news
Evidence
title: Fix issue pointer when insert to elastic
participants: @rachadiannovansyah @tukangremot @ayocodingit @indraprasetya154
> Fix issue pointer when insert to elastic

- core-service/src/modules/area/repository/mysql/mysql_area.go
- core-service/src/modules/news/usecase/news_ucase.go
Overview
Hotfix prod
- handling unlimited news
- return an empty array if not found on the areas repo
Evidence
title: Hotfix production portal Jabar
participants: @rachadiannovansyah @Ibwedagama @feriahmad
> hotfix production unlimited live news

- core-service/src/domain/feedback.go
Minor add max length increase by 10 (10 for prefix of sector"
cc: @jabardigitalservice/jds-backend
> increase max length of sector for prefix value

- core-service/src/modules/feedback/repository/mysql/mysql_feedback_test.go
Overview
update unit test of the `feedback` module
Evidence
title: Menambahkan unit test of module feedback
participants: @rachadiannovansyah @sandisunandar99 @indraprasetya154 @ayocodingit
> update unit test of feedback module

- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/modules/feedback/repository/mysql/mysql_feedback_test.go
- core-service/src/modules/feedback/usecase/feedback_ucase.go
Overview
- Add sanitizing request feedback
- Update unit test
Evidence
title: Menambahkan sanitasi kritik dan saran
participants: @rachadiannovansyah @rindibudiaramdhan @imamdev93 @indraprasetya154 @ayocodingit
> Feedback feature/add sanitizing request

- core-service/src/modules/feedback/usecase/feedback_ucase.go
Overview
Add sanitizing request from scripts attack
Evidence
title: Update sanitasi feedback untuk request script
> prevent script inject on feedback

- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/modules/feedback/usecase/feedback_ucase.go
Overview
sanitize emoticon request
- emoticon will disappear on storing to database
Ex result:
Evidence
title: Melakukan sanitasi request emoticon feedback
participants: @rachadiannovansyah @indraprasetya154 @rhmnmbr83 @ayocodingit
> remove emoji from the request

- core-service/src/domain/news.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
- core-service/src/modules/news/usecase/news_ucase.go
Overview
add counting endpoint to add view
Evidence
title: Menambahkan endpoint untuk menambahkan views
participants: @rachadiannovansyah @ayocodingit @indraprasetya154 @rindibudiaramdhan
> Create separate endpoint to counting views

- core-service/src/domain/news.go
- core-service/src/helpers/getters.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/usecase/news_ucase.go
Overview
- Add get counter views API
- Change the key of Redis
Evidence
title: Mengubah key redis dan menambahkankan get api counter
participants: @rachadiannovansyah @ayocodingit @rindibudiaramdhan
> Add get api counter news by slug

- core-service/src/helpers/getters.go
- core-service/src/helpers/helper.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
Overview:
Mitigation SQL injection
Condition:
- most values from the input use parameterized queries
Changes:
- prevent anomaly request who came from params filter
source of ref: https://www.stackhawk.com/blog/golang-sql-injection-guide-examples-and-prevention/
Evidence
title: Membuat regex params input untuk mitigasi sql injection
participants: @rachadiannovansyah @ayocodingit @rindibudiaramdhan
> adjust using parameterized queries

- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/repository.go
- core-service/src/cmd/server/usecase.go
- core-service/src/database/migrations/20220825022241_create_document_archives_table.down.sql
- core-service/src/database/migrations/20220825022241_create_document_archives_table.up.sql
- core-service/src/domain/document_archive.go
- core-service/src/helpers/helper.go
- core-service/src/modules/document-archive/delivery/http/public_document_archive_handler.go
- core-service/src/modules/document-archive/repository/mysql/mysql_document_archive.go
- core-service/src/modules/document-archive/repository/mysql/mysql_document_archive_helper.go
- core-service/src/modules/document-archive/usecase/document_archive_ucase.go
Overview:
Add New Module Document Archive
Changes:
- add new column migration `document_archives` table
- add new modules list documents archive
Evidence
title: Menambahkan modul list arsip dan dokumen
> Module Document Archive

- core-service/src/domain/document_archive.go
Overview
- Adjust struct `ListDocumentArchive/`
Evidence
title: Melakukan penyesuaian struct response document archive
> adjust struct for list document archive

- core-service/src/database/migrations/20220906035823_add_column_ppid_on_units_table.down.sql
- core-service/src/database/migrations/20220906035823_add_column_ppid_on_units_table.up.sql
- core-service/src/domain/unit.go
- core-service/src/modules/unit/repository/mysql/mysql_unit.go
Add column `ppid` on units table
- add new migration to add column
- adjust repo and resp to include `ppid`
Evidence
title: Menambahkan dan melakukan penyesuaian PPID dalam Perangkat Daerah
participants: @rachadiannovansyah @sandisunandar99 @ayocodingit @imamdev93
> Feature units/add column ppid

- core-service/src/domain/unit.go
Add resp `phone` on unit info
Sheet:
https://docs.google.com/spreadsheets/d/1gCfXALyKNJaYi7fWpBsL8RAM2QavE1xtF2fEzOyQOms/edit#gid=992914021
Evidence
title: Menambahkan response phone 
participants: @rachadiannovansyah @sandisunandar99 @rindibudiaramdhan @ayocodingit
> add resp phone on unit

- core-service/src/domain/news.go
Add struct response for APTIKA
Evidence
title: Menambahkan response requirement APTIKA
participants: @rachadiannovansyah @azophy @ayocodingit
> add res author & source on aptika resp

- core-service/src/helpers/getters.go
- core-service/src/helpers/redis.go
- core-service/src/middleware/permission.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
Add Dependency Injection Redis
Evidence
title: Redis improvements portal Jabar
> Dependency injection redis

- core-service/src/modules/search/repository/elastic/elastic_search.go
Add fuzzy query on global search 
Evidence
title: Menambahkan fuzzy query pada global search
> enhance query search add fuzziness

- core-service/src/domain/jsonhandle.go
- core-service/src/domain/public_service.go
Adjust struct Posters response
Example:
Evidence
title: Penyesuaian struct response poster
participants: @rachadiannovansyah @ayocodingit @muhamadabduh
> adjust struct poster response

- core-service/src/domain/public_service.go
- core-service/src/modules/public-service/delivery/http/public_service_handler.go
Add response facilities (array of object types)
Evidence
title: Penyesuaian structs response facilities
> add facilities struct res

- core-service/src/modules/public-service/repository/mysql/mysql_public_service.go
Now default filter on the list module `Layanan Publik` using the category
Evidence
title: Penyesuaian list layanan publik
> fix counting default list by category

- core-service/src/domain/redis.go
- core-service/src/helpers/setters.go
- core-service/src/middleware/permission.go
- core-service/src/modules/news/delivery/http/public_news_handler.go
Hotfix issue cache on pagination
Evidence
title: Hotfix caching halaman paginasi berita
> hotfix cache paginate news

- core-service/src/go.mod
- core-service/src/helpers/getters.go
Fix warning go mod & relocation structs
Evidence
title: Fix warning go mod 
> Fix minor coding style

- core-service/src/database/migrations/20221013073017_create_general_informations_table.down.sql
- core-service/src/database/migrations/20221013073017_create_general_informations_table.up.sql
- core-service/src/database/migrations/20221013073024_create_service_public_table.down.sql
- core-service/src/database/migrations/20221013073024_create_service_public_table.up.sql
Add new migration general_information & service_public
Evidence
title: Menambahkan migrasi structure database general_information & service_public
> Migration general_information & service_public tables

- core-service/src/modules/service-public/delivery/http/service_public_handler.go
- core-service/src/modules/service-public/repository/mysql/mysql_service_public.go
- core-service/src/modules/service-public/repository/mysql/mysql_service_public_helper.go
- Add an optional filter with parameterized queries
- Fix meta counts
Evidence
title: Menambahkan filter dan meta counts
participants: @rachadiannovansyah @ayocodingit @sandisunandar99 @rindibudiaramdhan
> Add optional parameterized queries on filter public service

- core-service/src/modules/search/delivery/http/search_handler.go
- core-service/src/modules/search/repository/elastic/elastic_search.go
Now fuzziness can change using params filters
Evidence
title: Menambahkan fuzziness flagging fitur global search
> now fuzziness can changed by params filter

- core-service/src/domain/service_public.go
change naming of res based on [API Spec](https://www.notion.so/Portal-Jabar-RFD-API-Contract-Halaman-Layanan-Publik-1e96bf43e94e4f57b63631ee17235b09)
Evidence
title: Penyesuaian naming response layanan publik
participants: @rachadiannovansyah @ayocodingit @rhmnmbr83 @imamdev93
> change naming res based on contract api

- core-service/src/database/migrations/20221021104701_alter_table_collation_and_charset_news_table.down.sql
- core-service/src/database/migrations/20221021104701_alter_table_collation_and_charset_news_table.up.sql
migration to chage `charset` and `collation` news table
Evidence
title: Membuat migration untuk merubah charset and collation tabel berita
participants: @rachadiannovansyah @ayocodingit @imamdev93
> alter charset and collation news table

- core-service/src/domain/service_public.go
- core-service/src/modules/service-public/delivery/http/service_public_handler.go
fix response of `facility` and `terms of service`
Facility
Terms of Service
Evidence
title: Penyesuaian struct response
> fix response facility and terms

- core-service/src/domain/service_public.go
add `omitempty` on struct `public-service`
Evidence
title: Menambahkan omitempty pada object layanan publik
participants: @rachadiannovansyah @ayocodingit @imamdev93 @rhmnmbr83
> add omitempty on struct public-service

- core-service/src/helpers/getters.go
- core-service/src/modules/news/repository/mysql/mysql_news_helper.go
add binding optional params on `news` domain
Evidence
title: Refactor params bind filter domain news
participants: @rachadiannovansyah @ayocodingit @sandisunandar99
> add binding optional params filter on domain news

- core-service/src/cmd/server/handler.go
- core-service/src/go.mod
- core-service/src/go.sum
- core-service/src/helpers/newrelic.go
- core-service/src/modules/service-public/delivery/http/service_public_handler.go
- core-service/src/modules/service-public/repository/mysql/mysql_service_public.go
- core-service/src/modules/service-public/usecase/service_public_ucase.go
- core-service/src/utils/apm.go
- core-service/src/utils/connection.go
- add integration `nrmysql` with newrelic
- no longer needed `zerolog`
- for example implement it on `public-service` module
Ex:
Todo:
next exprment to make dig a deep detailed APM database query
Evidence
title: Menambahkan database tracer new relic portal jabar
participants: @rachadiannovansyah @ayocodingit @sandisunandar99
> New relic/database tracer module `Layanan Publik`

- core-service/src/modules/service-public/delivery/http/service_public_handler.go
- add cache for api `/` and `/slug/:slug`
Evidence
title: Menanambahkan caching pada fitur layanan publik
participants: @rachadiannovansyah @ayocodingit @sandisunandar99 @rhmnmbr83
> add cache service-public api

- core-service/src/domain/general_information.go
- core-service/src/domain/service_public.go
- core-service/src/modules/general-information/repository/mysql/general_information.go
- core-service/src/modules/service-public/delivery/http/service_public_handler.go
- core-service/src/modules/service-public/repository/mysql/mysql_service_public.go
- core-service/src/modules/service-public/repository/mysql/mysql_service_public_test.go
- core-service/src/modules/service-public/usecase/service_public_ucase.go
- feat: add endpoint update (service-public)
- refactor naming struct store and update
- title: feat: add endpoint update (service-public)
- project: Portal Jabar
- participants: @ayocodingit @rachadiannovansyah
> feat: add endpoint update (service-public)

- core-service/src/cmd/migrater/main.go
- add engine indexing popular service
Evidence
title: Membuat engine indexing global search untuk layanan terpopuler
participants: @rachadiannovansyah @ayocodingit @rindibudiaramdhan
> add engine for indexing popular service

- core-service/src/modules/feedback/usecase/feedback_ucase_test.go
- core-service/src/modules/service-public/usecase/service_public_ucase.go
- core-service/src/modules/service-public/usecase/service_public_ucase_test.go
- add `TestMain` for preparing before a test and after the test 
- add more `assertion` on `feedback` also `service-public` module
Evidence
title: Improvement unit test dan menambah pengujian
> Improve unit test

- core-service/src/modules/service-public/usecase/service_public_ucase_test.go
- add `TestStore` and `TestUpdate` insted of mock of database transaction `sql.Tx` 
Evidence
title: Menambahkan unit test DB transaction mock module Layanan Publik
> fulfilled all unit test service-public module

- core-service/src/cmd/main.go
- core-service/src/cmd/migrater/main.go
- core-service/src/cmd/server/handler.go
- core-service/src/cmd/server/repository.go
- core-service/src/helpers/logger.go
- core-service/src/middleware/logger.go
- core-service/src/middleware/middleware.go
- core-service/src/modules/news/repository/mysql/mysql_news.go
- core-service/src/modules/news/repository/mysql/mysql_news_test.go
- setup custom logger with logrus
- initiated middleware
Note:
- test on staging, next will try to use https://github.com/jabardigitalservice/golog
Disclaimer: 
- in this pull request only testin on news domain
Evidence
title: Melakukan improvement terhadap logging aplikasi Portal Jabar
participants: @rachadiannovansyah @ayocodingit @tukangremot
> improve logging: add custom logger and middleware

- core-service/src/cmd/server/handler.go
- core-service/src/go.mod
- core-service/src/go.sum
- implement [golog](https://github.com/jabardigitalservice/golog) package on middleware logging
Evidence
title: Implement Golog Package on Portal Jabar
participants: @rachadiannovansyah @ayocodingit @tukangremot
> implement golog package for logging

- core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go
- core-service/src/domain/pop_up_banner.go
- core-service/src/domain/result.go
- core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go
- core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop up banner module): Add store endpoint
- add use case test store api
Figma's:
Evidence
title: Membuat API simpan pop up banner CMS Portal Jabar
participants: @rachadiannovansyah @rhmnmbr
> feat(pop up banner module): Add store endpoint

- core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go
- core-service/src/domain/pop_up_banner.go
- core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go
- core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop-up-banners): add update API endpoint
- add attr `end_date` on detail response
https://app.clickup.com/t/860pjr5yx
Test Result 
Evidence
title: Create API endpoint update pop-up banner CMS
participants: @rachadiannovansyah @rhmnmbr
> - feat(pop-up-banners): add update api endpoint

- core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go
- core-service/src/domain/pop_up_banner.go
- core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go
- core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- fix(pop-up-banners): issue when no one active
https://app.clickup.com/t/860pjr5yx
Evidence
title: Fix issue when no one pop-up banner active on update list CMS Portal Jabar
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit @rhmnmbr @muhamadabduh
> fix: issue when no-one active

- service-worker/src/cmd/main.go
- service-worker/src/job/pop_up_banner_deactive_job.go
- feat(service-worker): add job to deactivate pop-up banner
https://app.clickup.com/t/860pjr5xj
Result when the job is running:
Evidence
title: Add a cron job to deactivate pop-up banner every middle of the night
participants: @rachadiannovansyah @rhmnmbr @iqbal167 @imamdev93 @ayocodingit
> feat(service-worker): add cron job to deactivate pop up banner

- service-worker/src/cmd/main.go
- service-worker/src/job/news_archive_job.go
- service-worker/src/job/news_publishing_job.go
- service-worker/src/job/pop_up_banner_activate_job.go
- service-worker/src/job/pop_up_banner_deactive_job.go
- feat(service-worker): fix panic instance, service worker
- set @daily to news archiving & publishing worker
https://app.clickup.com/t/860pjr5xj
Result when the job is running:
Evidence
title: Fix panic instance service worker
> feat(service-worker): fix panic instance service worker

- core-service/src/domain/pop_up_banner.go
- core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go
- core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go
- core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner_test.go
- feat(pop-up-banner): add is_live property on pop up banner
Result test:
Evidence
title:  add is_live properly on pop-up banner
> feat(pop-up-banner): add is_live propery on pop up banner

- service-worker/src/job/pop_up_banner_deactive_job.go
feat(service-worker): update query worker
Evidence
title: Fix query service worker deactivate pop-up banner
participants: @rachadiannovansyah @rhmnmbr @imamdev93
> feat(service-worker): update query worker

- core-service/src/domain/pop_up_banner.go
- core-service/src/modules/pop-up-banner/delivery/http/public_pop_up_banner_handler.go
- feat(pop-up-banner): live banner response struct adjust
Evidence
title: Adjust response live banner
participants: @rachadiannovansyah @ayocodingit @rindibudiaramdhan @rhmnmbr @iqbal167 @imamdev93
> feat(pop-up-banner): live banner response struct adjust

- service-worker/docker/Dockerfile
- svc-worker-feat(service worker): fix docker file tz worker to neutral tz
Evidence
title: fix dockerfile tz service worker
participants: @rachadiannovansyah @Ibwedagama
> svc-worker-feat(service worker): fix dockerfile tz worker

- service-worker/src/job/pop_up_banner_deactive_job.go
- svc-worker-feat(deactivate-job): fix deactivate job query
Evidence
title: fix issue worker deactivates job scheduler
participants: @rachadiannovansyah @indraprasetya154 @iqbal167 @imamdev93 @ayocodingit
> svc-worker-feat(deactive-job):fix deactivate job query

- core-service/src/modules/news/usecase/news_ucase.go
- fix web view `link` not updated when editing news
https://app.clickup.com/t/860q0f6m4
Result test:
Evidence
title: Fix minor bug web view link not updated when editing news
participants: @rachadiannovansyah @ayocodingit @rhmnmbr @iqbal167
> core-svc-feat(news): fix web view link not updated when editing news

- core-service/src/domain/main_service.go
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_helper.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add API list endpoint
- completed with meta response
https://app.clickup.com/t/860pxrr96
Evidence
title: create API list endpoint master data service CMS portal jabar
participants: @rachadiannovansyah @iqbal167 @ayocodingit
> core-svc-feat(master data service): add api list endpoint

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_test.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add API delete endpoint
- also add test on the repository
https://app.clickup.com/t/860py69mr
Test Result
Evidence
title: create API delete endpoint master data service CMS portal jabar
participants: @rachadiannovansyah @iqbal167 @ayocodingit @rhmnmbr
> core-svc-mds(feat): add api delete mds

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- adjust the response list of value `operational_status` instead of `technical` service value
https://app.clickup.com/t/860pxrr96
Evidence
title: adjust API list response of master data service
participants: @rachadiannovansyah @rhmnmbr @indraprasetya154 @samudra-ajri @ayocodingit
> core-svc-feat(master-data-service): add api list endpoint

- core-service/src/domain/additional_information.go
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add API view Detail Master Data Service endpoint
https://app.clickup.com/t/860pxrumz
Evidence
title: add API view detail master data service endpoint
> core-svc-feat(master-data-service): add api view detail mds endpoint

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add API tabs status aggregations
https://app.clickup.com/t/860pxrr96
Evidence
title: add API tabs status aggregation master data cms portal jabar
participants: @rachadiannovansyah @ayocodingit @rhmnmbr
> core-svc-feat(master-data-service): add tabs status aggreations api

- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_helper.go
- add filter by `status` on mds list
https://app.clickup.com/t/860pxrr96
Evidence
title: add filter status on mds list
participants: @rachadiannovansyah @iqbal167 @ayocodingit
> core-svc-feat(master-data-service): add filter status on list mds

- core-service/src/domain/additional_information.go
- core-service/src/domain/applications.go
- core-service/src/domain/main_service.go
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- core-service/src/modules/mds-additional-information/repository/mysql/mysql_additional_information.go
- core-service/src/modules/mds-application/repository/mysql/mysql_mds_application.go
- core-service/src/modules/mds-main-service/repository/mysql/mysql_main_service.go
- core-svc-feat(master data service): add store MDS feature
- also use tx on here process
https://app.clickup.com/t/860pxruwd
Evidence
title: create API endpoint update of MDS feature CMS Portal Jabar
> core-svc-feat(master-data-service): add api endpoint update MDS

- core-service/src/modules/spbe-rals/repository/mysql/mysql_spbe_rals.go
- remove unused code on SPBE RALS
Evidence
title: refactor spbe rals list
participants: @rachadiannovansyah @rhmnmbr @ayocodingit
> core-svc-feat(master-data-service): remove unused code on spbe rals

- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- update the timestamp process
- remove unused constructor repository
Evidence
title: update the timestamp process and remove unused constructor on MDS feature
participants: @rachadiannovansyah @rindibudiaramdhan @iqbal167
> core-svc-feat(master-data-service): update the timestamp process and remove unused constructor

- core-service/src/database/migrations/20230403043306_add_column_is_active_and_title_on_applications_table.down.sql
- core-service/src/database/migrations/20230403043306_add_column_is_active_and_title_on_applications_table.up.sql
- core-service/src/domain/applications.go
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- core-service/src/modules/mds-application/repository/mysql/mysql_mds_application.go
- migration alters application table
- adjustment structs based on needs
Migration result
- Run migration on staging
Evidence
title: add alter migration table and adjustment struct master data layanan
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit @rhmnmbr @muhamadabduh @imamdev93
> core-svc-feat(master-data-service): adjust struct and migration application domain

- core-service/src/domain/applications.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- adjust struct type to `NullString` based on needs
Evidence
title: fix minor issue NullString value 
participants: @rachadiannovansyah @ayocodingit @indraprasetya154 @iqbal167 @rindibudiaramdhan
> core-svc-feat(master-data-service): adjust struct type to `NullString` based on needs

- .github/workflows/app-build-push.yml
- .github/workflows/app-release.yml
- .github/workflows/app-worker-build-push.yml
- .github/workflows/app-worker-release.yml
- .github/workflows/ci.yml
- core-service/docker/Dockerfile
- service-worker/docker/Dockerfile
infra: set-new-registry & improvement ci/cd
- title: infra: set-new-registry & improvement ci/cd
- project: Portal Jabar
- participants: @feriahmad @rachadiannovansyah
> infra: set-new-registry & improvement ci/cd

- .github/workflows/app-release.yml
- .github/workflows/app-worker-release.yml
infra: set-image-release ci/cd
- title: infra: set-image-release ci/cd
- project: Portal Jabar
- participants: @feriahmad @rachadiannovansyah
> infra: set-image-release ci/cd

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add API endpoint list archives with method `GET`
Evidence
title: add archives list master data services endpoint
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit @iqbal167 @indraprasetya154
> core-svc-feat(master-data-service): add archives list mds endpoint

- core-service/src/modules/search/delivery/http/search_handler.go
Changes:
- hotfix error slice bonds out
Evidence
title: fix error handling slice bonds out
participants: @rachadiannovansyah @Ibwedagama @doohanas
> core-svc-feat(global-search): hotfix error slice bonds out

- core-service/src/domain/master_data_publication.go
- core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
- core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
- core-service/src/modules/master-data-publication/usecase/publication_ucase.go
add API endpoint detail master data `publications` 
- path: `/v1/master-data-publications/:id`
- method: `GET`
Evidence
title: add api endpoint detail publication
> core-svc-feat(publications): add api endpoint detail publication

- core-service/src/domain/master_data_publication.go
- core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
- core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
- core-service/src/modules/master-data-publication/usecase/publication_ucase.go
add API endpoint tab list status aggregations master data `publications` 
- path: `/v1/master-data-publications/tabs`
- method: `GET`
Evidence
title: add api endpoint tabs list aggregations
participants: @rachadiannovansyah @ayocodingit @iqbal167 @rhmnmbr
> core-svc-feat(publications): add api endpoint tabs list aggregations

- core-service/src/modules/master-data-publication/usecase/publication_ucase.go
- minor fix: wrong use value of `mds_id`
Evidence
title: fix use case of publikasi
participants: @rachadiannovansyah @rhmnmbr @samudra-ajri @ayocodingit @imamdev93 @iqbal167
> core-svc-feat(publications): fix usecase to choose mds id

- core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- minor: fix not found the response of master data service
Existing: 
Now:
Evidence
title: fix not found the response of master data service
participants: @rachadiannovansyah @rhmnmbr @iqbal167 @ayocodingit @samudra-ajri
> core-svc-feat(masterdata-service): fix not found res

- core-service/src/domain/master_data_publication.go
- core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
- minor: add `ID` res on detail API publication
Evidence
title: add `ID` res on detail API publication
participants: @rachadiannovansyah @muhamadabduh @iqbal167 @ayocodingit
> core-svc-feat(publication): add res id for deleting act

- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- fix soft-deleted counting result on `Tab Status` Master Data Layanan
Evidence
title: fix soft-deleted counting result on `Tab Status` Master Data Layanan
participants: @rachadiannovansyah @rhmnmbr @iqbal167 @ayocodingit
> core-svc-feat(mds): fix counting of soft delete tab status

- core-service/src/database/migrations/20230515073556_add_column_created_by_on_mds_table.down.sql
- core-service/src/database/migrations/20230515073556_add_column_created_by_on_mds_table.up.sql
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_helper.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
-  add migration created_by on master data service table
-  fix access rights of mds
Evidence
title: fix hak akses user opd master data layanan
> core-svc-feat(mds): fix access rights OPD of mds service

- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/policies/mds_policy.go
-  add forbidden when no-authorized user opd access
Evidence
title: fix policy opd master data layanan
participants: @rachadiannovansyah @rhmnmbr
> core-svc-feat(masterdata_service): add policy master data service

- core-service/src/cmd/server/usecase.go
- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- core-service/src/policies/mds_policy.go
-  set policies based on each opd's
https://app.clickup.com/t/860qvn2yq
Evidence
title: set policies based on each opd's
> core-svc-feat(mds): set policies based on each opd's

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_helper.go
- add validate social media `TIKTOK`
- fix ambiguous status field
Evidence
title:  add validate social media tiktok master data layanan
participants: @rachadiannovansyah @indraprasetya154 @rhmnmbr @iqbal167 @ayocodingit
> core-svc-feat(mds): add validate social media tiktok master data layanan

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds_helper.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- add left join on query tabs aggregations status master data layanan
- now every opd's has a different value of counting layanan
Evidence
title:  fix counting master data service on each role opd's
> core-svc-feat(mds): fix counting master data service on each role opd's

- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- fix bug pagination role group admin
Evidence
title:  ix bug pagination role group admin
participants: @rachadiannovansyah @ayocodingit @rhmnmbr
> core-svc-feat(mds): fix bug pagination role group admin

- core-service/src/cmd/server/usecase.go
- core-service/src/domain/master_data_publication.go
- core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
- core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go
- core-service/src/modules/master-data-publication/usecase/publication_ucase.go
- core-service/src/policies/publication_policy.go
- add policy publication
- add forbidden access for unauthorized opd
https://app.clickup.com/t/860qajzxu
Evidence
title:  add forbidden access for unauthorized opd
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit
> core-svc-feat(publication): add policy publication

- core-service/src/modules/unit/repository/mysql/mysql_unit.go
- hotfix counting filters units opd
Evidence
title: hotfix counting filters unit opd
> core-svc-feat(units): hotfix counting filters unit opd

- core-service/src/domain/master_data_service.go
- core-service/src/modules/master-data-service/delivery/http/mds_handler.go
- core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go
- core-service/src/modules/master-data-service/usecase/mds_ucase.go
- remove default pagination on list archives
- add repository if archiving master data layanan
Evidence
title: no longer pagination on list archives master data layaban
participants: @rachadiannovansyah @ayocodingit @rhmnmbr
> core-svc-feat(publications): no longer pagination on list archives
