core-service/src/config/db.go, core-service/src/database/migrations/20210906032833_add_column_priority_on_event_table.down.sql, core-service/src/database/migrations/20210906032833_add_column_priority_on_event_table.up.sql, core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.down.sql, core-service/src/database/migrations/20210916020704_add_column_priorities_on_events_table.up.sql, core-service/src/repositories/mysql/mysql_event.go
Overview:
- Re-migration schema add priorities column
- add some logic to get data per week and sort it by `priorities` also `created_at`
cc: @jabardigitalservice/jds-backend
=> Feature agenda

core-service/src/repositories/mysql/mysql_event.go
Overview:
- Front End no longer send params sort_order and sort_by, used this by default by API
Evidence:
title: Default API sorting
participants: @novansyaah @khihadysucahyo @f1reFr0st @firmanalamsyah580 @sandisunandar @firman_desadigital
=> FE no longer send sort order & sort by, used this by default

core-service/src/cmd/main.go, core-service/src/delivery/http/event_handler.go, core-service/src/delivery/http/featured_program_handler.go, core-service/src/delivery/http/feedback_handler.go, core-service/src/delivery/http/handlers.go, core-service/src/delivery/http/informations_handler.go, core-service/src/delivery/http/news_handler.go, core-service/src/delivery/http/unit_handler.go
- Add http error handler
- http handler: returning error exception instead of json return
title: Add http error handler
participants: @khihadysucahyo @novansyaah @firmanJS @ayocodingit
=> add http error handler

core-service/src/database/migrations/1629281242_initialize_schema.up.sql, core-service/src/domain/featured_program.go, core-service/src/modules/featured-program/delivery/http/featured_program_handler.go, core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go, core-service/src/modules/featured-program/usecase/featured_program_ucase.go
Overview:
- Add filter to search categories based on jsonsearch SQL
reference here: https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-search
TO DO:
- Multiple category (on params)
Evidence:
title: add filter featured program with json search SQL
participants: @rachadiannovansyah @khihadysucahyo @ayocodingit @satemertua
Disc on @setiadijoe : this SQL injection haven't been refactored as yesterday as you want, because we have any task remaining :seedling:
=> add filter featured program with json search sql

core-service/src/modules/event/repository/mysql/mysql_event.go, core-service/src/modules/news/repository/mysql/mysql_news.go
- fix meta: represents the amount of data after filtering
Evidence:
title: fix meta: represents the amount of data after filtering
participants: @rachadiannovansyah @khihadysucahyo @firmanJS
=> fix meta total

core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- Fix meta didn't work on events
Evidence:
title: Fix meta didn't work on event
participants: @rachadiannovansyah @khihadysucahyo @firmanhxc @setiadijoe @ayocodingit
=> fix meta on events

core-service/src/database/migrations/1629281242_initialize_schema.up.sql, core-service/src/domain/event.go, core-service/src/modules/event/repository/mysql/mysql_event.go, core-service/src/modules/event/usecase/event_ucase.go
- Remove category object
- Category now only text (string)
title: no longer use category as obj on events
participants: @rachadiannovansyah @khihadysucahyo @sandisunandar99 
Temporary move to draft, Will merge on Monday (req by FE)
=> no longer use category as obj on events

core-service/src/modules/event/repository/mysql/mysql_event.go, core-service/src/modules/featured-program/repository/mysql/mysql_featured_program.go, core-service/src/modules/information/repository/mysql/mysql_informations.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/unit/repository/mysql/mysql_unit.go
Overview:
- Add query blocking of json_search (with multiple choice case)
- A lit refactor silly code
Evidence:
title: Add query block of multiple JSON Search
participants: @rachadiannovansyah @khihadysucahyo @firmanJS
=> Add query block of multiple JSON Search

core-service/src/domain/search.go, core-service/src/helpers/getters.go, core-service/src/helpers/mapper.go, core-service/src/modules/search/delivery/http/search_handler.go, core-service/src/modules/search/repository/elastic/elastic_search.go
- [fixed issue camelcase](https://github.com/mitchellh/mapstructure/pull/99): setting up a tag `mapstructure:"created_at" `
- added elastic aggregation mapvalue helper
- implement [post_filter](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-post-filter.html) to apply filter, after aggregations have already been calculated
- setup env for index name
- search sort order
- reviewing the use of [Types of multimatch query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#multi-match-types)
title: Search aggregation & apply post filter
participants: @khihadysucahyo @firmanJS @rachadiannovansyah @tukangremot
=> Search aggregation & apply post filter

core-service/src/domain/search.go, core-service/src/helpers/elastic.go, core-service/src/modules/search/repository/elastic/elastic_search.go
- change `createdAt` & `updatedAt` to` time.Time`
- added `ParseESDate` helper to parse elastic date string to time format
cc @jabardigitalservice/jds-backend 
title: Parse elastic date string to time format
participants: @khihadysucahyo @rachadiannovansyah @firmanJS @tukangremot @ayocodingit
=> Parse elastic date string to time format

core-service/src/middleware/jwt.go
- throw status unathorized instead of bad request if token isn't valid
title: handle throw status unathorized instead of bad request if token isn't valid
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @bangunbagustapa
=> throw status unathorized instead of bad request if token isn't valid

core-service/src/domain/event.go, core-service/src/modules/event/usecase/event_ucase.go
Overview:
- fill data tags on the event use case to show the current tag on each agenda
Evidence:
title: fill data tags on usecase agenda
participants: @rachadiannovansyah @khihadysucahyo @sandisunandar99 @ayocodingit
=> fill data tags on usecase agenda

core-service/src/domain/news.go, core-service/src/modules/news/delivery/http/news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/usecase/news_ucase.go
- added update status usecase
- manually enum status validator (still lookin best practice for this case #todo)
- setup cron to archiving news basen on start/publish date and duration
- policy to update status
title: added news status update feature
=> news status update feature

core-service/src/modules/tag/delivery/http/tag_handler.go, core-service/src/modules/tag/repository/mysql/mysql_tag.go
Overview:
- Add limit default for tags suggestion (reason -> references: tags medium)
- Throw if no longer keyword provided (for saving repo with not hit them)
Evidence:
title: Menambahkan empty state + limit tags
=> Give default limit for tags suggestion

core-service/src/domain/event.go, core-service/src/domain/news.go, core-service/src/modules/event/usecase/event_ucase.go, core-service/src/modules/news/usecase/news_ucase.go
Overview:
- Add timestamps res on store news
- Add timestamps res on store event
Evidence:
title: Fix timestamps on store news & agenda
=> Add timestamps on store news & store event

core-service/src/domain/tag.go, core-service/src/modules/event/usecase/event_ucase.go, core-service/src/modules/news/usecase/news_ucase.go, core-service/src/modules/tag/repository/mysql/mysql_tag.go
Overview:
- Prevent to add same tags if exists
Evidence:
title: Menambahkan kondisi pada penyimpanan tags domain
participants: @rachadiannovansyah @khihadysucahyo @ayocodingit @sandisunandar99
=> Prevent to add same tags if exists

core-service/src/helpers/converter.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/repository/mysql/mysql_news_test.go, core-service/src/modules/news/usecase/news_ucase.go
- make slug func
- only generate slug when status published
- added helper `ConvertTimeToString`
- adjust select props on news lists test by adding `startDate` and `endDate`
- converting binding startDate and endDate to string before use an existing updateReposiory, (updateRequest struct receive a string)
title: make slug on published
participants: @khihadysucahyo @rachadiannovansyah @ayocodingit @rindibudiaramdhan
=> make slug on published

core-service/src/helpers/converter.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/usecase/news_ucase.go
- added MakeSlug Helper
- set temporary and unique slug before create based on `(title-unix())`
- update unique slug based on `(title-newsID)` on published
=> set temporary and unique slug based on news id

core-service/src/database/migrations/20220217073352_add_column_published_at_on_news_table.up.sql, core-service/src/database/migrations/20220304034055_add_column_created_by_on_events_table.down.sql, core-service/src/database/migrations/20220304034055_add_column_created_by_on_events_table.up.sql, core-service/src/helpers/converter.go, core-service/src/modules/event/delivery/http/event_handler.go, core-service/src/modules/event/repository/mysql/mysql_event.go
Overview:
- add helper to convert slice to string
- modify endpoint filter to received multiple params value categories
- also add schema migration `created_by`
Evidence:
title: Multiple filter params category event
participants: @rachadiannovansyah @khihadysucahyo @rizkyrmsyah @sandisunandar99 @ayocodingit
=> Multiple filter params category event

core-service/src/domain/data_tag.go, core-service/src/domain/news.go, core-service/src/helpers/setters.go, core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go, core-service/src/modules/event/usecase/event_ucase.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/repository/mysql/mysql_news_test.go, core-service/src/modules/news/usecase/news_ucase.go
- news: improved store & update
- use pointer of time.Time instead of sql.Nulltime on PublishedAt prop
- passing domain param on delete data tag
title: use pointer of time.Time instead of sql.Nulltime on PublishedAt prop
=> use pointer of instead of sql.Nulltime

core-service/src/cmd/server/handler.go, core-service/src/cmd/server/repository.go, core-service/src/cmd/server/usecase.go, core-service/src/database/migrations/20220322120539_create_reg_invitations_table.down.sql, core-service/src/database/migrations/20220322120539_create_reg_invitations_table.up.sql, core-service/src/domain/errors.go, core-service/src/domain/registration_invitation.go, core-service/src/modules/registration-invitation/delivery/http/mysql_registration_handler.go, core-service/src/modules/registration-invitation/delivery/http/registration_invitation_handler.go, core-service/src/modules/registration-invitation/repository/mysql/mysql_registration_invitation.go, core-service/src/modules/registration-invitation/usecase/registration_invitation_ucase.go
initialize registration registration feature
- added domain: registration-invitation
- added migration to create registration_invitations table
- added repo interface to handle data manipulation in registration_invitations table
- added invate usecase to handle logic of invitation
- added temporary providing token on invitation response
- Create Jobs/SendMailInvitation
- Job Dispatcher
- Interface to verify registration token
- should be delete invitation token on this response after implement email service
title: added PublishedAt prop on headline/newsbanner
=> initialize registration registration feature

core-service/src/database/migrations/20220329011016_add_last_active_on_users_table.down.sql, core-service/src/database/migrations/20220329011016_add_last_active_on_users_table.up.sql, core-service/src/domain/user.go, core-service/src/modules/auth/usecase/auth_ucase.go, core-service/src/modules/user/repository/mysql/mysql_user.go
Overview:
- adjust value name invitation null instead of empty string
- add new column migration `last_active` on user
- write last_active login user
- get value last_active on endpoint api get member list
Evidence:
title: add last active on users login & get it from api endpoint memberlist invitation
=> Enchancement API list member invitation

core-service/src/domain/user.go, core-service/src/modules/user/delivery/http/user_handler.go, core-service/src/modules/user/repository/mysql/mysql_user.go, core-service/src/modules/user/usecase/user_usecase.go
Overview:
- add endpoint to set user as administrator
- add validation current change password
Evidence:
title: create endpoint to set user as administrator
=> create endpoint to set user as administrator

core-service/src/domain/user.go, core-service/src/helpers/helper.go, core-service/src/modules/user/delivery/http/user_handler.go, core-service/src/modules/user/repository/mysql/mysql_user.go, core-service/src/modules/user/usecase/user_usecase.go
Overview:
- add endpoint to change email user
- check user password is valid to process change email user
- check unique email & check valid email format
Evidence: 
title: create endpoint change email user partial
=> create endpoint change email user partial

core-service/src/domain/permission.go, core-service/src/modules/event/delivery/http/event_handler.go, core-service/src/modules/news/delivery/http/news_handler.go, core-service/src/modules/user/delivery/http/user_handler.go
set permission to endpoints (users, news, agenda
set permission to endpoint:
Users:
- List User
- Get User By Id
- Set User As Admin
- Change User Email
- Activate / Deactivate User
Agenda:
- List Agenda
- Get Agenda By Id
- Store Agenda
- Update Agenda
- Delete Agenda
News:
- Store News
- Get News By Id
- Update News
- Delete News
title: set permission to endpoints users, news, agenda
=> set permission to endpoints user, news, agenda

core-service/src/domain/permission.go, core-service/src/domain/user.go, core-service/src/modules/user/delivery/http/user_handler.go, core-service/src/modules/user/repository/mysql/mysql_user.go, core-service/src/modules/user/usecase/user_usecase.go
fix change status permission instead of activate account
- change permission activate-account to change-status
- change endpoint path, usecase, module function to "/users/:id/change-status"
title: fix change status permission instead of activate account
=> fix change-status permission instead of activate-account

core-service/src/domain/errors.go, core-service/src/modules/auth/usecase/auth_ucase.go, core-service/src/modules/user/repository/mysql/mysql_user.go
add condition when login to make sure user status is active
- add scan attribute status on repo get user by email
- add domain err user is not active
- add condition to check user is already active 
title: add condition when login to make sure user status is active
=> add condition when login to make sure user status is active

core-service/src/modules/user/usecase/user_usecase.go
- add validation email exists from invitation table
title: add check email exists from invitation table
=> add check email exists from invitation table

core-service/src/database/migrations/20220411060845_add_column_reporter_editor_on_news_table.down.sql, core-service/src/database/migrations/20220411060845_add_column_reporter_editor_on_news_table.up.sql, core-service/src/domain/news.go, core-service/src/modules/news/delivery/http/news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/repository/mysql/mysql_news_test.go, core-service/src/modules/news/usecase/news_ucase.go
Add new struct reporter, editor on news module
- add new migration to change **author_id** to **author**, also add new column **reporter** and **editor**
- putting of author object instead of created by object
- adjust response to add author, reporter, editor as a string
- adjust related endpoint (store, update, fetch, getbyid, newsbanner)
title: Add new struct reporter, editor on news module
=> Add new struct reporter, editor on news module

core-service/src/domain/news.go, core-service/src/modules/news/delivery/http/news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/usecase/news_ucase.go
Fix counting tabs status news role contributor
- add condition when contributor role only show his own tabs count news with their id
title: fix counting tabs status news role contributor
=> fix counting tabs status news role contributor

core-service/src/modules/event/usecase/event_ucase.go, core-service/src/modules/news/usecase/news_ucase.go
Fix issue ticket:
- Add trim tags to avoid over length on input tags
Evidence:
title: Add trim tags to avoid over length on input tags
=> add trim to fix over length tags

core-service/src/modules/event/delivery/http/event_handler.go, core-service/src/policies/event_policy.go
mitigate unauthorized user access endpoint detail
- add policy authorized user on endpoint detail agenda
title: add policy authorized user on event
=> add policy authorized user on api detail event

core-service/src/modules/news/delivery/http/public_news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news_helper.go
seems like portal use singular `cat` param instead of `cat[]` ,  during prod preparation and maybe takes time to have some context switching to fixing this bug, I propose this category filter to be able filter as string or slice
=> allow string/slice on category filter

core-service/src/cmd/migrater/main.go, core-service/src/modules/user/repository/mysql/mysql_user.go
- add excerpt on engine migrater to sync data public service
- add user last active on detail user
title: menambahkan excerpt pada migrater public service elastic
=> add excerpt on engine migrater to sync data public service

core-service/src/go.mod, core-service/src/modules/data-tag/repository/mysql/mysql_data_tag.go, core-service/src/modules/news/delivery/http/public_news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news_helper.go
now can filter news by tags from data tag domain
title: menambahkan filter berita berdasarkan tags 
participants: @rachadiannovansyah @indraprasetya154 @sandisunandar99
=> add filter tag news based on domain data tag

core-service/src/domain/search.go, core-service/src/helpers/elastic.go, core-service/src/modules/news/usecase/news_ucase.go, core-service/src/modules/search/repository/elastic/elastic_search.go
Overview
Add attribute **published_at** value on global search 
- adjust use case news
- adjust elastic repo
- use *time.Time to mitigate NullTime value
Evidence
title: enchancement global search terkait published berita
participants: @rachadiannovansyah @sandisunandar99 @tukangremot @rindibudiaramdhan @indraprasetya154 @Ibwedagama @ayocodingit @imamdev93
=> Sync published at on news elastic

service-worker/src/cmd/main.go, service-worker/src/go.mod, service-worker/src/go.sum
Overview
set cron to neutral time server (GMT)
Evidence
title: penyesuai default time service worker
participants: @rachadiannovansyah @indraprasetya154 @ayocodingit @tukangremot @sandisunandar99
=> fix time server to run cron

core-service/src/modules/news/usecase/news_ucase.go
Overview
fix insert to db then elastic on update news 
Evidence
title: fix bug update news 
participants: @rachadiannovansyah @ayocodingit @sandisunandar99 @indraprasetya154
=> fix insert to db then elastic on update news

core-service/src/domain/news.go, core-service/src/modules/news/delivery/http/public_news_handler.go, core-service/src/modules/news/usecase/news_ucase.go
Overview
update news public API for integration with APTIKA
- add news list response for aptika
- add params flagging
- add layer area on news usecase
Evidence
title: update publik API beria untuk OPD (Aptika)
participants: @rachadiannovansyah @rindibudiaramdhan @indraprasetya154 @ayocodingit @imamdev93
=> update news public API for integration with APTIKA

core-service/src/cmd/server/repository.go, core-service/src/config/redis.go, core-service/src/domain/news.go, core-service/src/domain/redis.go, core-service/src/go.mod, core-service/src/go.sum, core-service/src/helpers/getters.go, core-service/src/middleware/permission.go, core-service/src/modules/news/delivery/http/public_news_handler.go, core-service/src/modules/news/repository/mysql/mysql_news_test.go, core-service/src/modules/news/usecase/news_ucase.go, core-service/src/utils/connection.go
Overview
Implement Redis on Public API
- create own Middleware to check `verify cache`
- set it to public API (slug news api)
- change attribute type of `NullString`, `NullTime`, `NullInt` instead of Pointer
Evidence
title: Redis cache on public API to enhance performance
=> Implement Redis-Go on Public API

core-service/src/database/migrations/20220803070120_add_column_sector_on_feedback_tables.up.sql, core-service/src/domain/feedback.go, core-service/src/modules/feedback/repository/mysql/mysql_feedback.go, core-service/src/modules/feedback/usecase/feedback_ucase.go
Overview
adjust response api
- no longer need `updated_at` column on feedback
Evidence
title: Penyesuaian response feedback
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit
=> module feedback response adjustment

core-service/src/cmd/server/handler.go
Overview
- No longer use rate limiter on App
- Now rate limiter are adjusting on `ingress`
Evidence
title: Menghilangkan rate limiter aplikasi, beralih menggunakan ingress
participants: @rachadiannovansyah @indraprasetya154 @ayocodingit
=> remove rate limiter app

core-service/src/cmd/server/handler.go, core-service/src/cmd/server/repository.go, core-service/src/cmd/server/usecase.go, core-service/src/database/migrations/20220901051558_add_column_category_and_is_active_on_public_services_table.down.sql, core-service/src/database/migrations/20220901051558_add_column_category_and_is_active_on_public_services_table.up.sql, core-service/src/domain/public_service.go, core-service/src/modules/public-service/delivery/http/public_service_handler.go, core-service/src/modules/public-service/repository/mysql/mysql_public_service.go, core-service/src/modules/public-service/usecase/public_service_ucase.go
New API for Public Services
- alter the migration column to add fields `category` and `is_active`
- binding a request and using parameters queries to mitigate SQL injection
- add post API to store & index to elastic search
- add delete API to un-indexing data from elastic search
Evidence
title: Menambahkan fungsi untuk indexing data layanan public
=> Public service/api indexing

core-service/src/modules/search/repository/elastic/elastic_search.go
Adjust Query Elasticsearch to use `_score` for sorting result data
- no longer use sort on query
Evidence
title: Penyesuaian query elasticsearch
participants: @rachadiannovansyah @sandisunandar99 @ayocodingit @rindibudiaramdhan @imamdev93
=> no longer use sort on query search

core-service/src/helpers/setters.go, core-service/src/modules/news/usecase/news_ucase.go
Update use case set live props news
- if end date news has expired, now admin still can make it publish
- the start and end date are adjusted by currentTime admin publish + duration of news
Evidence
title: Penyesuaian proses publish berita
=> update use case set prop live news

core-service/src/helpers/setters.go
Update condition if the news is set to unlimited live or end_date is not nil/empty
Evidence
title: Penyesuaian berita tanpa batas
=> add condition if unlimited live or end date is null

core-service/src/modules/search/repository/elastic/elastic_search.go
Add combined scores and another sort
- set the `track_scores` is true will still be computed and tracked `_scores`
- now can sort with other values
Evidence
title: Enhance feature global search
participants: @rachadiannovansyah @sandisunandar99 @tukangremot @rindibudiaramdhan @ayocodingit @imamdev93
=> add track_scores on query elastic

core-service/src/cmd/migrater/main.go
Add new attribute 'published_at' on engine migrater
Evidence
title: Menambahkan attribute baru pada engine migrater elastic
participants: @rachadiannovansyah @rindibudiaramdhan @ayocodingit
=> add attrib `published_at` on migrater engine

core-service/src/helpers/redis.go, core-service/src/modules/news/delivery/http/public_news_handler.go
No longer use `URL.Path` now uses `URL.RequestURI`
title: Penyesuaian key cache redis
participants: @rachadiannovansyah @sandisunandar99 @ayocodingit @rhmnmbr83
=> update key cache using path query

core-service/src/modules/public-service/delivery/http/public_service_handler.go, core-service/src/modules/public-service/repository/mysql/mysql_public_service.go, core-service/src/modules/public-service/repository/mysql/mysql_public_service_helper.go
Add (optional) filter by type and keywords
- add custom params for `service_type`
- add mysql public service helper for optional filter
still seeing best practice for `optional filter`
Evidence
title: Menambahkan optional filter untuk service_type dan keywords layanan publik
=> add optional filter by type and keywords

core-service/src/domain/news.go, core-service/src/modules/news/repository/mysql/mysql_news.go, core-service/src/modules/news/usecase/news_ucase.go
Adjust use case API endpoint get by slug
- No longer can view archived news by using API `news/slug/:slug`
- 1 is equal to published and 0 is equal unpublished/archived
Evidence
title: Penyesuaian use case Berita by slug
participants: @rachadiannovansyah @sandisunandar99 @rhmnmbr83 @ayocodingit @imamdev93
=> make api by slug is only for published news

core-service/src/domain/result.go, core-service/src/domain/service_public.go, core-service/src/modules/service-public/delivery/http/service_public_handler.go, core-service/src/modules/service-public/repository/mysql/mysql_service_public.go, core-service/src/modules/service-public/usecase/service_public_ucase.go
- add `staticCount` property to meta data service public
- still provide propery counts not `null` when no data result
Evidence
title: Menambahkan mekanismes static count di layanan publik
=> Add meta property counts public service

core-service/src/domain/media.go, core-service/src/modules/media/delivery/http/media_handler.go, core-service/src/modules/media/usecase/media_ucase.go
- add the domain bucket name of the filepath
- validate to certain only can create and input on the allowed naming bucket
Example bucket domain public-service:
Note:
The existing bucket of `news` is no root folder or "/"
Evidence
title: Menambahkan domain bucket name file path S3 Portal Jabar
participants: @rachadiannovansyah @sandisunandar99 @ayocodingit @rindibudiaramdhan
=> add domain bucket name on media upload

core-service/src/cmd/server/handler.go, core-service/src/modules/news/delivery/http/news_handler.go
- remove un-used `sentry-capture`
- remove un-used old API public news
now has been declared on https://github.com/jabardigitalservice/portal-jabar-services/blob/main/core-service/src/modules/news/delivery/http/public_news_handler.go
Evidence
title: Remove un-used func of news
=> Remove un-used news old-public api 

core-service/src/cmd/server/handler.go, core-service/src/config/app.go, core-service/src/go.mod, core-service/src/go.sum
- updating package [golog](https://github.com/jabardigitalservice/golog/releases/tag/v0.0.3).
- now `resp_body` not including on logging.
- turn on/off banner & port on dev/prod env.
Evidence
title: Update package golog & penyesuaian argument paramater.
participants: @rachadiannovansyah @tukangremot @ayocodingit
=> update golog version & disable logging resp body

core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner_test.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop up banner module): Add get by id endpoint
- Add use case test and repository test
Figma's:
Response:
Test result:
Evidence
title: Membuat API get by id & unit test
participants: @rachadiannovansyah @ayocodingit @rhmnmbr @iqbal167
=> feat(pop up banner module): Add get by id endpoint & test

core-service/src/domain/media.go, core-service/src/modules/media/delivery/http/media_handler.go, core-service/src/modules/media/usecase/media_ucase.go
- feat(media):api-delete-object-s3
https://app.clickup.com/t/860pjr5xj
Because we're using versioning on S3 Bucket, so deleteObject only marks the object with the `Delete Marker` object type.
Evidence
title: Create API media to delete objects from S3
participants: @rachadiannovansyah @rhmnmbr @rindibudiaramdhan @ayocodingit @iqbal167
=> feat(media):api-delete-object-s3

core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/media/delivery/http/media_handler.go, core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
feat(pop up banner module): Add delete endpoint
- add use case test delete API
https://app.clickup.com/t/860pjr637
Test Result
Evidence
title: Create API endpoint delete pop-up-banner module CMS Portal Jabar
participants: @rachadiannovansyah @iqbal167
=> feat(pop up banner module): Add delete endpoint

core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop-up-banners): add patch status update API
- add use case test update status API
https://app.clickup.com/t/860pjr637
Test Result
Evidence
title: Create API endpoint partial update status pop up banner module CMS Portal Jabar
participants: @rachadiannovansyah @rhmnmbr @iqbal167
=> feat(pop-up-banners):add patch status update api

core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go
- feat(pop-up-banners): add sort by filter and set default sort
- rules of default sort is by `status` then by `created_at` fields
https://app.clickup.com/t/860pjr5x8
Evidence
title: Add default sort CMS pop-up banner
participants: @rachadiannovansyah @rindibudiaramdhan @rhmnmbr @indraprasetya154 @samudra-ajri @imamdev93 @iqbal167
=> feat(pop-up-banners): add sort by filter and set default sort

core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- fix(pop-up-banners): rules of patch status by list
- updated time of update process
https://app.clickup.com/t/860pjr5yx
Evidence
title: Add rules of patching status on list pop-up banner CMS Portal Jabar
participants: @rachadiannovansyah @rhmnmbr @ayocodingit
=> fix(pop-up-banners):rules of patch status by list

core-service/src/cmd/server/handler.go, core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/pop-up-banner/delivery/http/public_pop_up_banner_handler.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop-up-banner): create a live banner on the landing page
- no need for restricted middleware on the endpoint
Result when the job is running:
Evidence
title: Create API Endpoint public live pop-up banner
participants: @rachadiannovansyah @rindibudiaramdhan @rhmnmbr
=> feat(pop-up-banner): create api live banner on landing page

service-worker/src/job/pop_up_banner_deactive_job.go
- feat(service-worker:) set `now()` on every job updated process
Evidence
title: update worker update time process CMS portal jabar
participants: @rachadiannovansyah @indraprasetya154 @samudra-ajri @iqbal167
=> [portal-jabarprov] feat(service-worker): set `now()` on every job updated process

core-service/src/domain/mocks/repositories/PopUpBannerRepositoryMocks.go, core-service/src/domain/pop_up_banner.go, core-service/src/modules/pop-up-banner/delivery/http/pop_up_banner_handler.go, core-service/src/modules/pop-up-banner/repository/mysql/mysql_pop_up_banner.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase.go, core-service/src/modules/pop-up-banner/usecase/pop_up_banner_ucase_test.go
- feat(pop-up-banner): add flag `is_scheduled` on scheduler process
- parse the status with the default value is "NON-ACTIVE"
Evidence
title: add the flag `is_scheduled` on the scheduler process 
participants: @rachadiannovansyah @ayocodingit @rhmnmbr
=> [portal-jabarprov] feat(pop-up-banner): add flag `is_scheduled` on scheduler process

core-service/src/domain/master_data_publication.go, core-service/src/modules/master-data-publication/delivery/http/publication_handler.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication_helper.go, core-service/src/modules/master-data-publication/usecase/publication_ucase.go
add API endpoint list master data `publications` 
- path: `/v1//master-data-publications`
- method: `GET`
- `status`: for a filter by status (`PUBLISH` or `ARCHIVE`)
- `q`: for filtering data by keywords
Evidence
title: create API endpoint publication list module
participants: @rachadiannovansyah @muhamadabduh @ayocodingit
=> core-svc-feat(publications): add list api endpoint of publication

core-service/src/domain/master_data_publication.go, core-service/src/modules/master-data-publication/delivery/http/publication_handler.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication_test.go, core-service/src/modules/master-data-publication/usecase/publication_ucase.go
add API endpoint delete master data `publications` 
- path: `/v1/master-data-publications/:id`
- method: `DELETE`
Evidence
title: create API endpoint delete publication
participants: @rachadiannovansyah @rhmnmbr @ayocodingit @iqbal167
=> core-svc-feat(publications): add api delete publication

core-service/src/domain/master_data_publication.go, core-service/src/modules/master-data-publication/delivery/http/publication_handler.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go, core-service/src/modules/master-data-publication/usecase/publication_ucase.go
add API endpoint update data master data `publications` 
- path: `/v1/master-data-publications/:id`
- method: `PUT`
Evidence
title: add API endpoint update publication
participants: @rachadiannovansyah @rhmnmbr @iqbal167 @ayocodingit
=> core-svc-feat(publications): add api endpoint update publication

core-service/src/database/migrations/20230517040938_remove_column_sub_service_type_on_main_services_table.down.sql, core-service/src/database/migrations/20230517040938_remove_column_sub_service_type_on_main_services_table.up.sql, core-service/src/domain/main_service.go, core-service/src/domain/master_data_service.go, core-service/src/modules/master-data-service/repository/mysql/mysql_mds.go, core-service/src/modules/mds-main-service/repository/mysql/mysql_main_service.go
- remove migration of column `sub_service_type`
- remove struct req and res of `sub_service_type`
Evidence
title:  no longer need `sub_service_type` struct
participants: @rachadiannovansyah @indraprasetya154 @rhmnmbr @ayocodingit @samudra-ajri @imamdev93
=> core-svc-feat(mds): no longer need `sub_service_type` struct

core-service/src/modules/unit/repository/mysql/mysql_unit.go, core-service/src/modules/unit/repository/mysql/mysql_unit_helper.go
- add an exception for super admin to fetch on units query
https://app.clickup.com/t/860qyfhhm
Evidence
title:  add an exception for super admin to fetch on units query
participants: @rachadiannovansyah @ayocodingit @indraprasetya154 @imamdev93
=> core-svc-feat(units): excluded superadmin as a units

core-service/src/domain/master_data_publication.go, core-service/src/modules/master-data-publication/delivery/http/publication_handler.go, core-service/src/modules/master-data-publication/repository/mysql/mysql_publication.go, core-service/src/modules/master-data-publication/usecase/publication_ucase.go
- adjust `TabStatus` endpoint to separate based on units opd
https://app.clickup.com/t/860qajxha
Evidence
title: fix status aggregation based on opd
=> core-svc-feat(publication): fix status aggregation based on opd

core-service/src/domain/master_data_service.go, core-service/src/modules/unit/repository/mysql/mysql_unit.go, core-service/src/modules/unit/repository/mysql/mysql_unit_helper.go
- synced hotfix from `v1.7.11-core-service` to main
- no longer need omit empty on `service_fee`
Evidence
title: no longer need omitempty on `service_fee`
participants: @rachadiannovansyah @rhmnmbr @ayocodingit
=> core-svc-feat(mds): no longer need omitempty on `service_fee`

core-service/src/domain/master_data_publication.go, core-service/src/modules/master-data-publication/delivery/http/publication_handler.go
- make `nullString` of service_fee struct type
- use helper func `getObjectFromString` to build the object of service_fee
Evidence
title: now `service_fee` publication is an object response
participants: @rachadiannovansyah @rhmnmbr @ayocodingit
=> core-svc-feat(publication): now `service_fee` publication is an object response
